from django.shortcuts import render

# for testing
from django.http import HttpResponse

# imports util.py that was provided to us
from . import util

# converts entries/*.md files to html
import markdown2

# regular expression module
import re

# defines functionS that render .html templates from encyclopedia/ 
#* requires arugment 'request' calls the 'name' from urls.py?
#* returns function 'render'
#* render takes request argument and renders the template argument
#* render can provide context argument {} to the template
#? {} is a dict of values, not sure how it is populated
#? dict key can be anything and can be called in html
#? dict value can be a Python variable or function, e.g. a function from util.py

# Index route
def index(request):
    return render(request, "encyclopedia/index.html", {
        # creates a dict where the key "entries" can be called in html and
        # where the single value is a list of entries generated by the list.entries function
        "entries": util.list_entries()
    })

# Gets a wiki entry
def wiki(request, title):
    entry = util.get_entry(title)
    if entry:
        formatted_entry = markdown2.markdown(entry)
        return render(request, "encyclopedia/wiki.html", {
            "title1": title, "entry1": formatted_entry
        })
    else:
        return render(request, "encyclopedia/no_entry.html")

# Returns search results
def search(request):
    title = request.POST.get('q')
    entry = util.get_entry(title)
    if entry:
        formatted_entry = markdown2.markdown(entry)
        return render(request, "encyclopedia/wiki.html", {
            "title": title, "entry_text": formatted_entry
        })
    else: 
        entries = util.list_entries()
        results = []
        # return HttpResponse(f"{entries} / {len(entries)} / {len(entries[0])}")
        for i in range(len(entries)):
            if (title in entries[i]) or (title.capitalize() in entries[i]) or (title.casefold() in entries[i]):
                results.append(entries[i])
                #return HttpResponse(f"{title} / {entries[i]} / {results}")
    return render(request, "encyclopedia/search.html", {
        "results": results
    })

# Allows a user to type out a new Wiki entry
def wiki_new(request):
    return render(request, "encyclopedia/wiki_new.html")

# Saves a new or edited Wiki entry
def wiki_save(request):
    title1 = request.POST.get('title1')
    entry1 = request.POST.get('entry1')
    util.save_entry(title1, entry1)
    return render(request, "encyclopedia/wiki_save.html", {
        "title1": title1, "entry1": entry1
    })

# Allows a user to edit a Wiki entry
def wiki_edit(request):
    title1 = request.POST.get('title1')
    entry1 = util.get_entry(title1)
    return render(request, "encyclopedia/wiki_edit.html", {
        "title1": title1, "entry1": entry1
    })
   
# Provides a random Wiki entry
def wiki_random(request):
    return render(request, "encyclopedia/wiki_random.html", {
        
    })
